ss2.as='After Stimulus';
s2.GA=GA';
s2.median_P2P_left=median_P2P_as_left';
s2.IQR_P2P_left=IQR_P2P_as_left';
s2.median_P2P_right=median_P2P_as_right';
s2.IQR_P2P_right=IQR_P2P_as_right';
s2.median_corr=median_corr_as';
s2.IQR_corr=IQR_corr_as';
s2.median_corr_curved=median_corr_curved_as';
s2.IQR_corr_curved=IQR_corr_curved_as';
s2.median_avgSpeed_left=median_avgSpeed_as_left';
s2.IQR_avgSpeed_left=IQR_avgSpeed_as_left';
s2.median_avgSpeed_right=median_avgSpeed_as_right';
s2.IQR_avgSpeed_right=IQR_avgSpeed_as_right';
s2.median_avgAcc_left=median_avgAcc_as_left';
s2.IQR_avgAcc_left=IQR_avgAcc_as_left';
s2.median_avgAcc_right=median_avgAcc_as_right';
s2.IQR_avgAcc_right=IQR_avgAcc_as_right';
s2.median_avgJerk_left=median_avgJerk_bs_left';
s2.IQR_avgJerk_left=IQR_avgJerk_as_left';
s2.median_avgJerk_right=median_avgJerk_as_right';
s2.IQR_avgJerk_right=IQR_avgJerk_as_right';

%%
ss1.bs='Before Stimulus';
s1.GA=GA';
s1.median_P2P_left=median_P2P_bs_left';
s1.IQR_P2P_left=IQR_P2P_bs_left';
s1.median_P2P_right=median_P2P_bs_right';
s1.IQR_P2P_right=IQR_P2P_bs_right';
s1.median_corr=median_corr_bs';
s1.IQR_corr=IQR_corr_bs';
s1.median_corr_curved=median_corr_curved_bs';
s1.IQR_corr_curved=IQR_corr_curved_bs';
s1.median_avgSpeed_left=median_avgSpeed_bs_left';
s1.IQR_avgSpeed_left=IQR_avgSpeed_bs_left';
s1.median_avgSpeed_right=median_avgSpeed_bs_right';
s1.IQR_avgSpeed_right=IQR_avgSpeed_bs_right';
s1.median_avgAcc_left=median_avgAcc_bs_left';
s1.IQR_avgAcc_left=IQR_avgAcc_bs_left';
s1.median_avgAcc_right=median_avgAcc_bs_right';
s1.IQR_avgAcc_right=IQR_avgAcc_bs_right';
s1.median_avgJerk_left=median_avgJerk_bs_left';
s1.IQR_avgJerk_left=IQR_avgJerk_bs_left';
s1.median_avgJerk_right=median_avgJerk_bs_right';
s1.IQR_avgJerk_right=IQR_avgJerk_bs_right';

%%
T=struct2table(ss1);
T1=struct2table(s1);
t=struct2table(ss2);
t1=struct2table(s2);
warning('off','MATLAB:xlswrite:AddSheet')
path1='F:\';
typ='.xls';
fna='Median_IQR_10_03272015';
fna1=strcat(path1,fna);
fname1=strcat(fna1,typ);
writetable(T,fname1,'sheet',1)
writetable(T1,fname1,'sheet',1,'Range','A3')
writetable(t,fname1,'sheet',1,'Range','A15')
writetable(t1,fname1,'sheet',1,'Range','A17')
